name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run tests without features
      run: cargo test --verbose --no-default-features
    - name: Run tests with std feature only
      run: cargo test --verbose --no-default-features --features std
    - name: Run tests with dataset
      run: cargo test --verbose --no-default-features --features dataset
    - name: Run tests with rand
      run: cargo test --verbose --no-default-features --features rand
